"""
Convert blog_articles_data.py (Python tuples) → TypeScript source snippet
suitable for pasting into src/lib/site-data.ts.

Output: /home/z/my-project/scripts/blog_articles_data.ts
"""
import sys
import json
import os
import importlib.util

SRC = "/home/z/my-project/scripts/blog_articles_data.py"

spec = importlib.util.spec_from_file_location("blog_articles_data", SRC)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
ARTICLES = mod.BLOG_ARTICLES
print(f"Loaded {len(ARTICLES)} articles", file=sys.stderr)

# Category normalization — map our raw categories to BlogPost category union
CATEGORY_MAP = {
    "AI / Chatbots": "AI Automation",
    "AI / Automation": "AI Automation",
    "SEO": "SEO",
    "Web Dev": "Web Dev",
    "Web Performance": "Web Dev",
    "Digital Marketing": "Digital Marketing",
    "E-commerce": "E-commerce",
    "Social Media": "Digital Marketing",
}

# Date string → ISO date
def to_iso(date_str: str) -> str:
    """Convert 'Aug 5, 2026' → '2026-08-05'."""
    from datetime import datetime
    try:
        return datetime.strptime(date_str, "%b %d, %Y").strftime("%Y-%m-%d")
    except Exception:
        return "2026-08-01"

# Read-time → tags derived from title + category
def derive_tags(title: str, category: str) -> list:
    t = title.lower()
    tags = []
    if "chatbot" in t: tags += ["ai-chatbot", "lead-qualification"]
    if "social" in t and "ecommerce" not in t: tags += ["social-media", "content-strategy"]
    if "ecommerce" in t or "e-commerce" in t: tags += ["ecommerce", "social-commerce"]
    if "seo" in t or "audit" in t: tags += ["seo", "audit"]
    if "pagespeed" in t or "next.js" in t or "next js" in t: tags += ["nextjs", "performance"]
    if "ai" in t and "automation" in t: tags += ["ai", "automation"]
    if "analytics" in t or "user behavior" in t: tags += ["analytics", "user-behavior"]
    if not tags: tags = [category.lower().replace(" ", "-")]
    return tags[:4]

out = []
out.append("// ─── BLOG (real articles, sourced from /blog_src/*.md) ───────────────────")
out.append("// AUTO-GENERATED by scripts/port_blog_to_ts.py — do not edit by hand.")
out.append("")
out.append("export const BLOG_POSTS: BlogPost[] = [")

for i, article in enumerate(ARTICLES):
    # Schema: slug, title, category, readTime, date, author, excerpt, heroImage, bodyHtml
    slug = article[0]
    title = article[1]
    raw_cat = article[2]
    read_time = article[3]
    date_str = article[4]
    author = article[5]
    excerpt = article[6]
    hero_image = article[7]
    body_html = article[8]

    category = CATEGORY_MAP.get(raw_cat, "Web Dev")
    iso = to_iso(date_str)
    tags = derive_tags(title, category)

    # Also produce a plain-text body excerpt for SEO/OG (first ~280 chars of excerpt)
    plain_body = excerpt

    out.append("  {")
    out.append(f"    slug: {json.dumps(slug)},")
    out.append(f"    title: {json.dumps(title)},")
    out.append(f"    excerpt: {json.dumps(excerpt)},")
    out.append(f"    category: {json.dumps(category)},")
    out.append(f"    author: {json.dumps(author)},")
    out.append(f"    publishedAt: {json.dumps(iso)},")
    out.append(f"    readTime: {json.dumps(read_time)},")
    out.append(f"    tags: {json.dumps(tags)},")
    out.append(f"    body: {json.dumps(plain_body)},")
    out.append(f"    heroImage: {json.dumps(hero_image)},")
    # Use JSON to safely escape the HTML body
    out.append(f"    bodyHtml: {json.dumps(body_html)},")
    out.append("  },")

out.append("];")
out.append("")

OUT_PATH = "/home/z/my-project/scripts/blog_articles_data.ts"
with open(OUT_PATH, "w") as f:
    f.write("\n".join(out))

print(f"Wrote {OUT_PATH}")
print(f"Size: {os.path.getsize(OUT_PATH)} bytes")
print(f"Articles: {len(ARTICLES)}")
