***REMOVED***!/usr/bin/env python3
"""
QA AUDIT — Link Integrity Checker
Extracts all internal hrefs from src/ (tsx/ts files) and checks them against
the actual route manifest generated by `next build`. Reports broken links.
"""
import os
import re
import json
import subprocess
from collections import defaultdict

ROOT = "/home/z/my-project"
SRC = os.path.join(ROOT, "src")

***REMOVED*** 1. Extract route manifest from .next build output
app_paths_dir = os.path.join(ROOT, ".next", "server", "app")
routes = set()

***REMOVED*** Static routes from filesystem
app_dir = os.path.join(SRC, "app")
for dirpath, dirnames, filenames in os.walk(app_dir):
    ***REMOVED*** Skip api routes (checked separately)
    if "/api" in dirpath.replace(app_dir, ""):
        continue
    rel = os.path.relpath(dirpath, app_dir)
    if rel == ".":
        continue
    ***REMOVED*** Normalize: [[...slug]] = optional catch-all, [slug] = dynamic
    parts = rel.split(os.sep)
    route = "/" + "/".join(parts)
    if "page.tsx" in filenames or "route.ts" in filenames:
        routes.add(route)

***REMOVED*** Expand dynamic routes from build manifest if available
build_routes = set()
manifest_path = os.path.join(ROOT, ".next", "app-path-routes-manifest.json")
if os.path.exists(manifest_path):
    try:
        with open(manifest_path) as f:
            m = json.load(f)
        build_routes = set(m.values()) | set(m.keys())
    except Exception:
        pass

***REMOVED*** From prerender manifest (has actual generated dynamic paths)
prerender_path = os.path.join(ROOT, ".next", "prerender-manifest.json")
dynamic_paths = set()
if os.path.exists(prerender_path):
    try:
        with open(prerender_path) as f:
            p = json.load(f)
        for k in p.get("routes", {}).keys():
            dynamic_paths.add(k)
    except Exception:
        pass

***REMOVED*** 2. Extract all internal hrefs from source files
href_pattern = re.compile(r'''(?:href|redirect|push|replace)\s*[=(]\s*["'`](/[^"'`\s?***REMOVED***]*)["'`]''')
href_tpl_pattern = re.compile(r'''href=\{?\s*[`"](/[^`"\}]*\{[^}]*\}[^`"\}]*)[`"]''')

links = defaultdict(list)  ***REMOVED*** link -> [files]
for dirpath, dirnames, filenames in os.walk(SRC):
    for fn in filenames:
        if not fn.endswith((".tsx", ".ts")):
            continue
        ***REMOVED*** Skip node_modules, api internals
        path = os.path.join(dirpath, fn)
        try:
            with open(path, encoding="utf-8", errors="ignore") as f:
                content = f.read()
        except Exception:
            continue
        for m in href_pattern.finditer(content):
            link = m.group(1)
            ***REMOVED*** Skip non-page links
            if link.startswith(("/api/", "/_next/", "/og-", "/clicktake-logo")):
                continue
            ***REMOVED*** Skip static assets with extensions
            if re.search(r"\.(png|jpg|jpeg|svg|webp|ico|xml|txt|css|js|json|mp4|webm|pdf)$", link):
                continue
            links[link].append(os.path.relpath(path, ROOT))

***REMOVED*** 3. Check each link
def normalize(r):
    return r.rstrip("/") or "/"

known_routes = set()
for r in routes:
    known_routes.add(normalize(re.sub(r"/\[\[?\.\.\.[^\]]+\]\]?", "", r)))
    known_routes.add(normalize(r))
for r in build_routes:
    rr = re.sub(r"/\(\.+\)", "", r)
    known_routes.add(normalize(rr))
for p in dynamic_paths:
    known_routes.add(normalize(p))

***REMOVED*** Known valid special routes
special = {"/", "/sitemap.xml", "/robots.txt", "/rss.xml", "/llms.txt",
           "/openapi.json", "/auth.md", "/admin", "/admin/login",
           "/legal", "/legal/privacy", "/legal/terms", "/legal/cookies"}

broken = []
checked = set()
for link, files in sorted(links.items()):
    norm = normalize(link)
    if norm in checked:
        continue
    checked.add(norm)
    ***REMOVED*** Dynamic template links like /blog/${slug} — skip (runtime-generated)
    if "${" in link or "{" in link:
        continue
    ***REMOVED*** Has query or hash — strip for check
    base = link.split("?")[0].split("***REMOVED***")[0] or "/"
    nb = normalize(base)
    if nb in special or nb in known_routes:
        continue
    ***REMOVED*** Check prefix match for catch-all routes
    prefix_ok = False
    for kr in known_routes:
        if kr != "/" and (nb.startswith(kr + "/") or nb == kr):
            prefix_ok = True
            break
    if prefix_ok:
        continue
    broken.append((link, sorted(set(files))[:3]))

print("=" * 70)
print("BROKEN INTERNAL LINKS (", len(broken), ")")
print("=" * 70)
for link, files in broken:
    print(f"  {link}")
    for f in files:
        print(f"      ↳ {f}")

print()
print("=" * 70)
print(f"TOTAL unique internal links checked: {len(checked)}")
print(f"Known routes: {len(known_routes)}")
print(f"Dynamic prerendered paths: {len(dynamic_paths)}")
print("=" * 70)
